### ISSUE TITLE
It doesn't work :(

### ISSUE THREAD

**Issue by Vadimatorik** [fastrizwaan/mhWaveEdit_flatpak#1]
1. I do:
```
# build
flatpak-builder --force-clean build-dir io.github.mhWaveEdit.yml
```
I got error message. But i solved it:
```
flatpak install flathub org.freedesktop.Platform/x86_64/20.08 
```
Please, add it to README :)

2. I do:
```
# run
flatpak run io.github.mhWaveEdit
```
But i see message:
```
mhwaveedit: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by fastrizwaan** [comment]
There's already created flatpak in the repo https://github.com/fastrizwaan/mhWaveEdit_flatpak/blob/main/mhWaveEdit.flatpak

```
https://github.com/fastrizwaan/mhWaveEdit_flatpak/raw/main/mhWaveEdit.flatpak
flatpak install mhWaveEdit.flatpak
flatpak run io.github.mhWaveEdit
```

**Comment by Vadimatorik** [comment]
> There's already created flatpak in the repo https://github.com/fastrizwaan/mhWaveEdit_flatpak/blob/main/mhWaveEdit.flatpak
> 
> ```
> https://github.com/fastrizwaan/mhWaveEdit_flatpak/raw/main/mhWaveEdit.flatpak
> flatpak install mhWaveEdit.flatpak
> flatpak run io.github.mhWaveEdit
> ```

Thank you for your answer. I did it:
```
flatpak run io.github.mhWaveEdit    
mhwaveedit: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by fastrizwaan** [comment]
did you first remove it?

```
flatpak remove io.github.mhWaveEdit 
```
then
```
https://github.com/fastrizwaan/mhWaveEdit_flatpak/raw/main/mhWaveEdit.flatpak
flatpak install mhWaveEdit.flatpak
flatpak run io.github.mhWaveEdit
```

**Comment by Vadimatorik** [comment]
> did you first remove it?
> 
> ```
> flatpak remove io.github.mhWaveEdit 
> ```
> 
> then
> 
> ```
> https://github.com/fastrizwaan/mhWaveEdit_flatpak/raw/main/mhWaveEdit.flatpak
> flatpak install mhWaveEdit.flatpak
> flatpak run io.github.mhWaveEdit
> ```

No... I didn't it( Thank you very much) It works)

**Comment by fastrizwaan** [comment]
hi, you could rebuild and install latest version with freedesktop 23.08


```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.freedesktop.Sdk/x86_64/23.08 org.freedesktop.Platform/x86_64/23.08 

git clone https://github.com/fastrizwaan/mhWaveEdit_flatpak.git

cd mhWaveEdit_flatpak


flatpak-builder --force-clean build-dir io.github.mhWaveEdit.yml
flatpak-builder --user --install --force-clean build-dir io.github.mhWaveEdit.yml

flatpak run io.github.mhWaveEdit
```

**Comment by fastrizwaan** [comment]
hi, I've submitted mhwaveedit to flathub, should be there in a couple of days. enjoy.
